/* Auto-generated by genmsg_java.py for file /opt/ros/fuerte/stacks/arm_navigation/arm_navigation_msgs/msg/SyncPlanningSceneResult.msg */

package ros.pkg.arm_navigation_msgs.msg;

import java.nio.ByteBuffer;

public class SyncPlanningSceneResult extends ros.communication.Message {

  public boolean ok;

  public SyncPlanningSceneResult() {
  }

  public static java.lang.String __s_getDataType() { return "arm_navigation_msgs/SyncPlanningSceneResult"; }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public static java.lang.String __s_getMD5Sum() { return "6f6da3883749771fac40d6deb24a8c02"; }
  public java.lang.String getMD5Sum() { return __s_getMD5Sum(); }
  public static java.lang.String __s_getMessageDefinition() { return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n" +
"bool ok\n" +
"\n" +
""; }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }

  public SyncPlanningSceneResult clone() {
    SyncPlanningSceneResult c = new SyncPlanningSceneResult();
    c.deserialize(serialize(0));
    return c;
  }

  public void setTo(ros.communication.Message m) {
    deserialize(m.serialize(0));
  }

  public int serializationLength() {
    int __l = 0;
    __l += 1; // ok
    return __l;
  }

  public void serialize(ByteBuffer bb, int seq) {
    bb.put((byte)(ok ? 1 : 0));
  }

  public void deserialize(ByteBuffer bb) {
    ok = bb.get() != 0 ? true : false;
  }

  @SuppressWarnings("all")
  public boolean equals(Object o) {
    if(!(o instanceof SyncPlanningSceneResult))
      return false;
    SyncPlanningSceneResult other = (SyncPlanningSceneResult) o;
    return
      ok == other.ok &&
      true;
  }

  @SuppressWarnings("all")
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    long tmp;
    result = prime * result + (this.ok ? 1231 : 1237);
    return result;
  }
} // class SyncPlanningSceneResult

