/* Auto-generated by genmsg_cpp for file /home/flavio/Works/Roboearth_iaslab/stacks/roboearth/re_srvs/srv/RequestProj2DMap.srv */
#ifndef RE_SRVS_SERVICE_REQUESTPROJ2DMAP_H
#define RE_SRVS_SERVICE_REQUESTPROJ2DMAP_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"



#include "re_msgs/RosFile.h"
#include "re_msgs/RosFile.h"

namespace re_srvs
{
template <class ContainerAllocator>
struct RequestProj2DMapRequest_ {
  typedef RequestProj2DMapRequest_<ContainerAllocator> Type;

  RequestProj2DMapRequest_()
  : envUID()
  , minZ(0.0)
  , maxZ(0.0)
  , targetMapName()
  {
  }

  RequestProj2DMapRequest_(const ContainerAllocator& _alloc)
  : envUID(_alloc)
  , minZ(0.0)
  , maxZ(0.0)
  , targetMapName(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _envUID_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  envUID;

  typedef double _minZ_type;
  double minZ;

  typedef double _maxZ_type;
  double maxZ;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _targetMapName_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  targetMapName;


  typedef boost::shared_ptr< ::re_srvs::RequestProj2DMapRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::re_srvs::RequestProj2DMapRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct RequestProj2DMapRequest
typedef  ::re_srvs::RequestProj2DMapRequest_<std::allocator<void> > RequestProj2DMapRequest;

typedef boost::shared_ptr< ::re_srvs::RequestProj2DMapRequest> RequestProj2DMapRequestPtr;
typedef boost::shared_ptr< ::re_srvs::RequestProj2DMapRequest const> RequestProj2DMapRequestConstPtr;


template <class ContainerAllocator>
struct RequestProj2DMapResponse_ {
  typedef RequestProj2DMapResponse_<ContainerAllocator> Type;

  RequestProj2DMapResponse_()
  : success(false)
  , map()
  , meta()
  {
  }

  RequestProj2DMapResponse_(const ContainerAllocator& _alloc)
  : success(false)
  , map(_alloc)
  , meta(_alloc)
  {
  }

  typedef uint8_t _success_type;
  uint8_t success;

  typedef  ::re_msgs::RosFile_<ContainerAllocator>  _map_type;
   ::re_msgs::RosFile_<ContainerAllocator>  map;

  typedef  ::re_msgs::RosFile_<ContainerAllocator>  _meta_type;
   ::re_msgs::RosFile_<ContainerAllocator>  meta;


  typedef boost::shared_ptr< ::re_srvs::RequestProj2DMapResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::re_srvs::RequestProj2DMapResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct RequestProj2DMapResponse
typedef  ::re_srvs::RequestProj2DMapResponse_<std::allocator<void> > RequestProj2DMapResponse;

typedef boost::shared_ptr< ::re_srvs::RequestProj2DMapResponse> RequestProj2DMapResponsePtr;
typedef boost::shared_ptr< ::re_srvs::RequestProj2DMapResponse const> RequestProj2DMapResponseConstPtr;

struct RequestProj2DMap
{

typedef RequestProj2DMapRequest Request;
typedef RequestProj2DMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct RequestProj2DMap
} // namespace re_srvs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::re_srvs::RequestProj2DMapRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::re_srvs::RequestProj2DMapRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::re_srvs::RequestProj2DMapRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "5ee9f7b02752843c2c8c2067dfffdef5";
  }

  static const char* value(const  ::re_srvs::RequestProj2DMapRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x5ee9f7b02752843cULL;
  static const uint64_t static_value2 = 0x2c8c2067dfffdef5ULL;
};

template<class ContainerAllocator>
struct DataType< ::re_srvs::RequestProj2DMapRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "re_srvs/RequestProj2DMapRequest";
  }

  static const char* value(const  ::re_srvs::RequestProj2DMapRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::re_srvs::RequestProj2DMapRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string envUID\n\
float64 minZ\n\
float64 maxZ\n\
string targetMapName\n\
\n\
\n\
";
  }

  static const char* value(const  ::re_srvs::RequestProj2DMapRequest_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::re_srvs::RequestProj2DMapResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::re_srvs::RequestProj2DMapResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::re_srvs::RequestProj2DMapResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "0b14b385997efc59caa091c489f65080";
  }

  static const char* value(const  ::re_srvs::RequestProj2DMapResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x0b14b385997efc59ULL;
  static const uint64_t static_value2 = 0xcaa091c489f65080ULL;
};

template<class ContainerAllocator>
struct DataType< ::re_srvs::RequestProj2DMapResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "re_srvs/RequestProj2DMapResponse";
  }

  static const char* value(const  ::re_srvs::RequestProj2DMapResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::re_srvs::RequestProj2DMapResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool success\n\
re_msgs/RosFile map\n\
re_msgs/RosFile meta\n\
\n\
\n\
================================================================================\n\
MSG: re_msgs/RosFile\n\
# This file representation is used to pass binary data to the RoboEarthDB.\n\
# As the endianess isn't stored, only files with a byte order mark (BOM) or\n\
# an implicitly specified endianess should be transferred.\n\
string name   # file name\n\
int8[] data   # binary data \n\
\n\
";
  }

  static const char* value(const  ::re_srvs::RequestProj2DMapResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::re_srvs::RequestProj2DMapRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.envUID);
    stream.next(m.minZ);
    stream.next(m.maxZ);
    stream.next(m.targetMapName);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct RequestProj2DMapRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::re_srvs::RequestProj2DMapResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.success);
    stream.next(m.map);
    stream.next(m.meta);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct RequestProj2DMapResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<re_srvs::RequestProj2DMap> {
  static const char* value() 
  {
    return "e0f2eef827fa0f11b6c20a347206ed51";
  }

  static const char* value(const re_srvs::RequestProj2DMap&) { return value(); } 
};

template<>
struct DataType<re_srvs::RequestProj2DMap> {
  static const char* value() 
  {
    return "re_srvs/RequestProj2DMap";
  }

  static const char* value(const re_srvs::RequestProj2DMap&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<re_srvs::RequestProj2DMapRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e0f2eef827fa0f11b6c20a347206ed51";
  }

  static const char* value(const re_srvs::RequestProj2DMapRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<re_srvs::RequestProj2DMapRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "re_srvs/RequestProj2DMap";
  }

  static const char* value(const re_srvs::RequestProj2DMapRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<re_srvs::RequestProj2DMapResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e0f2eef827fa0f11b6c20a347206ed51";
  }

  static const char* value(const re_srvs::RequestProj2DMapResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<re_srvs::RequestProj2DMapResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "re_srvs/RequestProj2DMap";
  }

  static const char* value(const re_srvs::RequestProj2DMapResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // RE_SRVS_SERVICE_REQUESTPROJ2DMAP_H

