/* Auto-generated by genmsg_cpp for file /home/flavio/Works/Roboearth_iaslab/stacks/roboearth/re_srvs/srv/SetEnvironment.srv */
#ifndef RE_SRVS_SERVICE_SETENVIRONMENT_H
#define RE_SRVS_SERVICE_SETENVIRONMENT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"

#include "re_msgs/File.h"



namespace re_srvs
{
template <class ContainerAllocator>
struct SetEnvironmentRequest_ {
  typedef SetEnvironmentRequest_<ContainerAllocator> Type;

  SetEnvironmentRequest_()
  : cls()
  , id()
  , description()
  , environment()
  , files()
  , apiKey()
  {
  }

  SetEnvironmentRequest_(const ContainerAllocator& _alloc)
  : cls(_alloc)
  , id(_alloc)
  , description(_alloc)
  , environment(_alloc)
  , files(_alloc)
  , apiKey(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _cls_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  cls;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _id_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  id;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _description_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  description;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _environment_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  environment;

  typedef std::vector< ::re_msgs::File_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::re_msgs::File_<ContainerAllocator> >::other >  _files_type;
  std::vector< ::re_msgs::File_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::re_msgs::File_<ContainerAllocator> >::other >  files;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _apiKey_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  apiKey;


  typedef boost::shared_ptr< ::re_srvs::SetEnvironmentRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::re_srvs::SetEnvironmentRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct SetEnvironmentRequest
typedef  ::re_srvs::SetEnvironmentRequest_<std::allocator<void> > SetEnvironmentRequest;

typedef boost::shared_ptr< ::re_srvs::SetEnvironmentRequest> SetEnvironmentRequestPtr;
typedef boost::shared_ptr< ::re_srvs::SetEnvironmentRequest const> SetEnvironmentRequestConstPtr;


template <class ContainerAllocator>
struct SetEnvironmentResponse_ {
  typedef SetEnvironmentResponse_<ContainerAllocator> Type;

  SetEnvironmentResponse_()
  : success(false)
  {
  }

  SetEnvironmentResponse_(const ContainerAllocator& _alloc)
  : success(false)
  {
  }

  typedef uint8_t _success_type;
  uint8_t success;


  typedef boost::shared_ptr< ::re_srvs::SetEnvironmentResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::re_srvs::SetEnvironmentResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct SetEnvironmentResponse
typedef  ::re_srvs::SetEnvironmentResponse_<std::allocator<void> > SetEnvironmentResponse;

typedef boost::shared_ptr< ::re_srvs::SetEnvironmentResponse> SetEnvironmentResponsePtr;
typedef boost::shared_ptr< ::re_srvs::SetEnvironmentResponse const> SetEnvironmentResponseConstPtr;

struct SetEnvironment
{

typedef SetEnvironmentRequest Request;
typedef SetEnvironmentResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct SetEnvironment
} // namespace re_srvs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::re_srvs::SetEnvironmentRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::re_srvs::SetEnvironmentRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::re_srvs::SetEnvironmentRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "66bb6647d3636e904b1f631496fd9074";
  }

  static const char* value(const  ::re_srvs::SetEnvironmentRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x66bb6647d3636e90ULL;
  static const uint64_t static_value2 = 0x4b1f631496fd9074ULL;
};

template<class ContainerAllocator>
struct DataType< ::re_srvs::SetEnvironmentRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "re_srvs/SetEnvironmentRequest";
  }

  static const char* value(const  ::re_srvs::SetEnvironmentRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::re_srvs::SetEnvironmentRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
string cls\n\
string id\n\
string description\n\
string environment\n\
re_msgs/File[] files\n\
\n\
string apiKey\n\
\n\
\n\
================================================================================\n\
MSG: re_msgs/File\n\
# This file representation is used to pass binary data to the RoboEarthDB.\n\
# As the endianess isn't stored, only files with a byte order mark (BOM) or\n\
# an implicitly specified endianess should be transferred.\n\
string name   # file name\n\
int8[] data   # binary data \n\
\n\
";
  }

  static const char* value(const  ::re_srvs::SetEnvironmentRequest_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::re_srvs::SetEnvironmentResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::re_srvs::SetEnvironmentResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::re_srvs::SetEnvironmentResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const  ::re_srvs::SetEnvironmentResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::re_srvs::SetEnvironmentResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "re_srvs/SetEnvironmentResponse";
  }

  static const char* value(const  ::re_srvs::SetEnvironmentResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::re_srvs::SetEnvironmentResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool success\n\
\n\
\n\
";
  }

  static const char* value(const  ::re_srvs::SetEnvironmentResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::re_srvs::SetEnvironmentResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::re_srvs::SetEnvironmentRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.cls);
    stream.next(m.id);
    stream.next(m.description);
    stream.next(m.environment);
    stream.next(m.files);
    stream.next(m.apiKey);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SetEnvironmentRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::re_srvs::SetEnvironmentResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.success);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SetEnvironmentResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<re_srvs::SetEnvironment> {
  static const char* value() 
  {
    return "f22e7a1df0f0163b3238a8fccf24e141";
  }

  static const char* value(const re_srvs::SetEnvironment&) { return value(); } 
};

template<>
struct DataType<re_srvs::SetEnvironment> {
  static const char* value() 
  {
    return "re_srvs/SetEnvironment";
  }

  static const char* value(const re_srvs::SetEnvironment&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<re_srvs::SetEnvironmentRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "f22e7a1df0f0163b3238a8fccf24e141";
  }

  static const char* value(const re_srvs::SetEnvironmentRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<re_srvs::SetEnvironmentRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "re_srvs/SetEnvironment";
  }

  static const char* value(const re_srvs::SetEnvironmentRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<re_srvs::SetEnvironmentResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "f22e7a1df0f0163b3238a8fccf24e141";
  }

  static const char* value(const re_srvs::SetEnvironmentResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<re_srvs::SetEnvironmentResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "re_srvs/SetEnvironment";
  }

  static const char* value(const re_srvs::SetEnvironmentResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // RE_SRVS_SERVICE_SETENVIRONMENT_H

