string objectUID  # unique identifier of the object
string apiKey     # the user's API key (get yours from 
                  # http://roboearth.informatik.uni-stuttgart.de)
---
bool success      # whether object was found and deleted
