(cl:defpackage re_2dmap_extractor-srv
  (:use )
  (:export
   "REQUESTLOCMAP"
   "<REQUESTLOCMAP-REQUEST>"
   "REQUESTLOCMAP-REQUEST"
   "<REQUESTLOCMAP-RESPONSE>"
   "REQUESTLOCMAP-RESPONSE"
   "REQUESTNAVMAP"
   "<REQUESTNAVMAP-REQUEST>"
   "REQUESTNAVMAP-REQUEST"
   "<REQUESTNAVMAP-RESPONSE>"
   "REQUESTNAVMAP-RESPONSE"
  ))

