/* Auto-generated by genmsg_cpp for file /opt/ros/fuerte/stacks/ias_common/vision_srvs/srv/register_jlo_callback.srv */

package ros.pkg.vision_srvs.srv;

import java.nio.ByteBuffer;


public class register_jlo_callback extends ros.communication.Service<register_jlo_callback.Request, register_jlo_callback.Response> {

  public static java.lang.String __s_getDataType() { return "vision_srvs/register_jlo_callback"; }
  public static java.lang.String __s_getMD5Sum() { return "4ebd0d41ee3295d3b5b92eeaa53db753"; }

  public java.lang.String getDataType() { return register_jlo_callback.__s_getDataType(); }
  public java.lang.String getMD5Sum() { return register_jlo_callback.__s_getMD5Sum(); }

  public register_jlo_callback.Request createRequest() {
    return new register_jlo_callback.Request();
  }

  public register_jlo_callback.Response createResponse() {
    return new register_jlo_callback.Response();
  }

static public class Request extends ros.communication.Message {

  public java.lang.String topic_name = new java.lang.String();
  public long jlo_id;
  public long parent_id;
  public double[] filter_delta_cov = new double[6];

  public Request() {
  }

  public static java.lang.String __s_getDataType() { return "vision_srvs/register_jlo_callbackRequest"; }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public static java.lang.String __s_getMD5Sum() { return "b4a1c7e4da9d58ce6fde17f373bed739"; }
  public java.lang.String getMD5Sum() { return __s_getMD5Sum(); }
  public static java.lang.String __s_getServerMD5Sum() { return "4ebd0d41ee3295d3b5b92eeaa53db753"; }
  public java.lang.String getServerMD5Sum() { return __s_getServerMD5Sum(); }
  public static java.lang.String __s_getMessageDefinition() { return "\n" +
"string topic_name\n" +
"uint64     jlo_id\n" +
"uint64     parent_id\n" +
"float64[6] filter_delta_cov\n" +
"\n" +
""; }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }

  public Request clone() {
    Request c = new Request();
    c.deserialize(serialize(0));
    return c;
  }

  public void setTo(ros.communication.Message m) {
    deserialize(m.serialize(0));
  }

  public int serializationLength() {
    int __l = 0;
    __l += 4 + topic_name.length();
    __l += 8; // jlo_id
    __l += 8; // parent_id
    __l += 48; // filter_delta_cov
    return __l;
  }

  public void serialize(ByteBuffer bb, int seq) {
    Serialization.writeString(bb, topic_name);
    bb.putLong(jlo_id);
    bb.putLong(parent_id);

    for(double val : filter_delta_cov) {
      bb.putDouble(val);
    }
  }

  public void deserialize(ByteBuffer bb) {
    topic_name = Serialization.readString(bb);
    jlo_id = bb.getLong();
    parent_id = bb.getLong();

    int __filter_delta_cov_len = filter_delta_cov.length;;
    filter_delta_cov = new double[__filter_delta_cov_len];
    for(int __i=0; __i<__filter_delta_cov_len; __i++) {
      filter_delta_cov[__i] = bb.getDouble();
    }
  }

  @SuppressWarnings("all")
  public boolean equals(Object o) {
    if(!(o instanceof Request))
      return false;
    Request other = (Request) o;
    return
      topic_name.equals(other.topic_name) &&
      jlo_id == other.jlo_id &&
      parent_id == other.parent_id &&
      java.util.Arrays.equals(filter_delta_cov, other.filter_delta_cov) &&
      true;
  }

  @SuppressWarnings("all")
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    long tmp;
    result = prime * result + (this.topic_name == null ? 0 : this.topic_name.hashCode());
    result = prime * result + (int)(this.jlo_id ^ (this.jlo_id >>> 32));
    result = prime * result + (int)(this.parent_id ^ (this.parent_id >>> 32));
    result = prime * result + java.util.Arrays.hashCode(this.filter_delta_cov);
    return result;
  }
} // class Request

static public class Response extends ros.communication.Message {

  public java.lang.String error = new java.lang.String();

  public Response() {
  }

  public static java.lang.String __s_getDataType() { return "vision_srvs/register_jlo_callbackResponse"; }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public static java.lang.String __s_getMD5Sum() { return "eca8b96616c32aacf1be8bbf14c70eba"; }
  public java.lang.String getMD5Sum() { return __s_getMD5Sum(); }
  public static java.lang.String __s_getServerMD5Sum() { return "4ebd0d41ee3295d3b5b92eeaa53db753"; }
  public java.lang.String getServerMD5Sum() { return __s_getServerMD5Sum(); }
  public static java.lang.String __s_getMessageDefinition() { return "string error\n" +
"\n" +
""; }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }

  public Response clone() {
    Response c = new Response();
    c.deserialize(serialize(0));
    return c;
  }

  public void setTo(ros.communication.Message m) {
    deserialize(m.serialize(0));
  }

  public int serializationLength() {
    int __l = 0;
    __l += 4 + error.length();
    return __l;
  }

  public void serialize(ByteBuffer bb, int seq) {
    Serialization.writeString(bb, error);
  }

  public void deserialize(ByteBuffer bb) {
    error = Serialization.readString(bb);
  }

  @SuppressWarnings("all")
  public boolean equals(Object o) {
    if(!(o instanceof Response))
      return false;
    Response other = (Response) o;
    return
      error.equals(other.error) &&
      true;
  }

  @SuppressWarnings("all")
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    long tmp;
    result = prime * result + (this.error == null ? 0 : this.error.hashCode());
    return result;
  }
} // class Response

} //class

