/* Auto-generated by genmsg_cpp for file /home/flavio/Works/Roboearth_iaslab/stacks/roboearth/re_msgs/msg/SeenObjectArray.msg */
#ifndef RE_MSGS_MESSAGE_SEENOBJECTARRAY_H
#define RE_MSGS_MESSAGE_SEENOBJECTARRAY_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "re_msgs/SeenObject.h"

namespace re_msgs
{
template <class ContainerAllocator>
struct SeenObjectArray_ {
  typedef SeenObjectArray_<ContainerAllocator> Type;

  SeenObjectArray_()
  : header()
  , object()
  {
  }

  SeenObjectArray_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , object(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::vector< ::re_msgs::SeenObject_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::re_msgs::SeenObject_<ContainerAllocator> >::other >  _object_type;
  std::vector< ::re_msgs::SeenObject_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::re_msgs::SeenObject_<ContainerAllocator> >::other >  object;


  typedef boost::shared_ptr< ::re_msgs::SeenObjectArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::re_msgs::SeenObjectArray_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct SeenObjectArray
typedef  ::re_msgs::SeenObjectArray_<std::allocator<void> > SeenObjectArray;

typedef boost::shared_ptr< ::re_msgs::SeenObjectArray> SeenObjectArrayPtr;
typedef boost::shared_ptr< ::re_msgs::SeenObjectArray const> SeenObjectArrayConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::re_msgs::SeenObjectArray_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::re_msgs::SeenObjectArray_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace re_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::re_msgs::SeenObjectArray_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::re_msgs::SeenObjectArray_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::re_msgs::SeenObjectArray_<ContainerAllocator> > {
  static const char* value() 
  {
    return "db06ee56fb2cfb4568deee7165cba35f";
  }

  static const char* value(const  ::re_msgs::SeenObjectArray_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xdb06ee56fb2cfb45ULL;
  static const uint64_t static_value2 = 0x68deee7165cba35fULL;
};

template<class ContainerAllocator>
struct DataType< ::re_msgs::SeenObjectArray_<ContainerAllocator> > {
  static const char* value() 
  {
    return "re_msgs/SeenObjectArray";
  }

  static const char* value(const  ::re_msgs::SeenObjectArray_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::re_msgs::SeenObjectArray_<ContainerAllocator> > {
  static const char* value() 
  {
    return "#This represents a list of objects\n\
Header header\n\
SeenObject[] object\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: re_msgs/SeenObject\n\
#This represents a Object\n\
time stamp\n\
string name\n\
geometry_msgs/Pose pose\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
";
  }

  static const char* value(const  ::re_msgs::SeenObjectArray_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::re_msgs::SeenObjectArray_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::re_msgs::SeenObjectArray_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::re_msgs::SeenObjectArray_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.object);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SeenObjectArray_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::re_msgs::SeenObjectArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::re_msgs::SeenObjectArray_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "object[]" << std::endl;
    for (size_t i = 0; i < v.object.size(); ++i)
    {
      s << indent << "  object[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::re_msgs::SeenObject_<ContainerAllocator> >::stream(s, indent + "    ", v.object[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // RE_MSGS_MESSAGE_SEENOBJECTARRAY_H

